version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: upendartodo123
      MYSQL_DATABASE: todo_app
      MYSQL_USER: upendartodo
      MYSQL_PASSWORD: upendartodo123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password



volumes:
  mysql_data:
